title: Project-Prime API Documents
description: Kernel, other API Docs
theme: just-the-docs

url: https://akki697222.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
